### ISSUE TITLE
Internal GC can leave Peers in inconsistent state

### ISSUE THREAD

**Issue by bboreham** [zettio/weave#367] opened 2015-01-26 14:23 UTC
Suppose we have three peers with three directed connections as follows:

1 <--> 2 --> 3

Then when node 3 does a GarbageCollect, it will remove node 1 as unreachable, while still retaining a reference to node 1 as a connection from node 2.  Node 2 is retained because it is 'locally referenced', i.e. there is a connection with 3.

If node 3 now tries to send this topology to another node that doesn't know 1, the update will be rejected as it mentions but does not contain node 1.

**Comment by rade** [comment] 2015-01-28 16:42
gc could consider all locally referenced peers as roots. This would ensure that sending the complete topology includes all peers referenced by connections. However, it won't prevent other nodes from gc'ing a bunch of peers. Consider a node 4, bidirectionally connected to 3. When it receives the complete topology from 3, it will remove 1 and 2, since the latter isn't locally referenced. This is bad because a subsequent incremental update for, say, a connection from 3 to 2, will be rejected.

The solution may be require us to move some way towards #374, namely including non-established connections in gossip.

**Comment by bboreham** [comment] 2015-01-28 16:55
What if we changed GC so it left things in the Peers collection if somebody claims to connect to them, even if we can't?

**Comment by rade** [comment] 2015-01-28 17:03
By "somebody claims to connect to them" do you mean "some peer has a connection to them"?

Then consider 1 <--> 2 <--> 3. Now the connection between 2 and 3 drops. 3 sees the connection drop so removes it from its connection list. But its records for 1 and 2 still contain the connection between them. Hence they meet the "some peer has a connection to them" criteria.

**Comment by rade** [comment] 2015-01-28 19:34
Matters aren't helped here by a change as a consequence of #313: a peer may now receive a topology from another peer prior to the connection to that peer being added to its connection list. So even including non-established connections doesn't help in some situations.

**Comment by rade** [comment] 2015-01-30 09:49
The issue here is even more subtle than it first appears, because

- The reachability analysis performed by the gc pays no attention to the 'established' flag. Consequently local, unestablished connections are considered valid paths to other nodes.

- When a connection is made between two peers, each peer will only mark the connection as 'established' after the other peer has entered the connection in their connection list. That is because the other peer sends the 'Established' protocol message after receiving a heartbeat packet over UDP, and the processing of that heartbeat packet is conditional on the connection appearing in the connection map.

- Only 'established' connections are included in topology communication.

Therefore the situation described in the initial comment cannot actually arise. The connection from 2 to 3 can only be marked as 'established' (and hence have been communicated to 3) if 3 has the connection to 2 in its connection map, which in turn prevents it from gc'ing both 2 and 3.

HOWEVER, a slight different scenario can give rise to gc-induced state inconsistency....

3 can become aware of 1<-->2 without the connection between itself and 2 having been marked as 'established' at either end, and, moreover, prior to the connection appearing in 3's connection map. That's because 2 might gossip the topology to 3 at any point after the connection appears in 2's connection map. On receiving that gossip, 3 won't gc 2, because that is locally referenced, but it will gc 1.

There are two easy ways to fix that:

1. Don't gossip over unestablished connections.

2. Make connection addition synchronous and perform it before we enter the tcp receive loop.

There are downsides to both. 1 requires an extra read lock on each connection for every gossip, in order to check for 'established'. It also runs counter to our goal of separating the control and data plane, as per #374. 2 carries the risk of deadlock (I believe it's safe, but more careful analysis is required).

And after this we are still left with the problem of [other nodes gc'ing away part of the topology](#issuecomment-71868509).

**Comment by rade** [comment] 2015-01-31 18:21
Steps to reproduce the inconsistency...

#### Step 1: patch & rebuild weave
```patch
diff --git a/router/gossip.go b/router/gossip.go
index 5c37422..8596b7c 100644
--- a/router/gossip.go
+++ b/router/gossip.go
@@ -8,7 +8,7 @@ import (
 	"time"
 )
 
-const GossipInterval = 30 * time.Second
+const GossipInterval = 3 * time.Second
 
 type Gossip interface {
 	// specific message from one peer to another
diff --git a/router/local_peer.go b/router/local_peer.go
index 0cbb3fd..418a46b 100644
--- a/router/local_peer.go
+++ b/router/local_peer.go
@@ -7,6 +7,8 @@ import (
 	"time"
 )
 
+var LocalPeerDelay = 0
+
 type LocalPeer struct {
 	*Peer
 	Router    *Router
@@ -166,6 +168,9 @@ func (peer *LocalPeer) queryLoop(queryChan <-chan *PeerInteraction) {
 			}
 			switch query.code {
 			case PAddConnection:
+				if LocalPeerDelay > 0 {
+					time.Sleep(time.Duration(LocalPeerDelay) * time.Second)
+				}
 				conn := query.payload.(*LocalConnection)
 				if peer.handleAddConnection(conn) {
 					conn.log("connection added")
diff --git a/weaver/main.go b/weaver/main.go
index de62f30..37916e5 100644
--- a/weaver/main.go
+++ b/weaver/main.go
@@ -55,6 +55,7 @@ func main() {
 	flag.StringVar(&prof, "profile", "", "enable profiling and write profiles to given path")
 	flag.IntVar(&connLimit, "connlimit", 10, "connection limit (defaults to 10, set to 0 for unlimited)")
 	flag.IntVar(&bufSz, "bufsz", 8, "capture buffer size in MB (defaults to 8MB)")
+	flag.IntVar(&weave.LocalPeerDelay, "delay", 0, "local peer processing delay (for testing, defaults to 0)")
 	flag.Parse()
 	peers = flag.Args()
```
This reduces the gossip interval (so we don't have to wait so long) and introduces a command line option to delay processing of `AddConnection` by `LocalPeer`.

#### Step 2: fire up 4 VMs containing weave
As of the https://github.com/zettio/weave/commit/5967d5de206321e896af82713eeb93bd6e1c98f4 it is easy to spin up an arbitrary number of VMs containing weave.

#### Step 3: start the weaves
...and construct an initial topology of two pairs
```
host1# weave launch
host2# weave launch host1-ip
host3# weave launch --delay=5
host4# weave launch host3-ip
```
Check the `weave status` on 3 and 4 until the connection between them is fully established in both directions

#### Step 4: connect the two pairs
```
host3# weave connect host2-ip
```

#### Step 5: check the logs on 4
In the presence of the issue the logs contain "Topology gossip: Reference to unknown peer ..." entries.

**Closed** 2015-01-31 22:32 UTC
Labels: bug

**Comment by rade** [comment] 2015-01-31 23:16
I have created #380 for the problem of [other nodes gc'ing away part of the topology](#issuecomment-71868509).
